app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # 商品一覧
  get '/',      to: 'list#index',  as: 'item_list'
  get '/items', to: 'list#index'
  # 商品詳細
  get '/items/:id', to: 'detail#index',  as: 'item_detail'
  # レビュー一覧
  get '/items/:id/reviews', to: 'review#index',  as: 'reviews'
  # レビュー投稿フォーム
  get '/items/:id/reviews/new', to: 'review#new',  as: 'review_new'
  # レビュー投稿
  post '/items/:id/review/create', to: 'review#create', as: 'review_create'
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/app/models/item.rb
class Item < ApplicationRecord
    # 商品を全て取得 パラメータに応じてソートする
    def select_items(sort_option)
        item_base = self.select_base_items
        case sort_option
        when 'rating' then
            return item_base.order(review_rating: :desc)
        when 'review' then
            return item_base.order(review_count: :desc)
        when 'latest' then
            return item_base.order(created_at: :desc)
        else
            return item_base.order(review_count: :desc)
        end
    end

    # item_idから商品情報を取得
    def select_by_id(item_id)
        item_base = self.select_base_items
        return item_base.find_by(id: item_id)
    end

    # 同じメーカーのIDを取得
    def select_by_maker_exclude_item_id(item_maker_id, item_id)
        item_base = self.select_base_items
        return item_base.where(item_maker_id: item_maker_id)
                        .where.not(id: item_id)
                        .order(review_count: :desc)
    end

    private
    
    # 商品情報のベースを取得
    def select_base_items
        return Item.select('
            items.id AS item_id, 
            items.item_name AS item_name, 
            items.item_price AS item_price, 
            items.item_image_path AS item_image_path, 
            items.item_sentence AS item_sentence, 
            items.item_maker_id AS item_maker_id, 
            mst_makers.maker_name AS maker_name, 
            mst_makers.maker_sentence AS maker_sentence, 
            mst_categories.category_name AS category_name, 
            COUNT(reviews.id) AS review_count, 
            if(COUNT(reviews.id) > 0,
                ROUND(AVG(reviews.review_rating), 1),
                0.0
            ) AS review_rating,
            items.created_at AS created_at
        ')
        .joins('INNER JOIN mst_makers ON mst_makers.id = items.item_maker_id')
        .joins('INNER JOIN mst_categories ON mst_categories.id = items.item_category_id')
        .joins('LEFT OUTER JOIN reviews ON reviews.item_id = items.id')
        .group('items.id')
    end
end

app/app/models/mst_category.rb
class MstCategory < ApplicationRecord
end

app/app/models/mst_maker.rb
class MstMaker < ApplicationRecord
end

app/app/models/mst_review_tag.rb
class MstReviewTag < ApplicationRecord
end

app/app/models/review.rb
class Review < ApplicationRecord
    attr_accessor :tag_names
    @tag_names = []

    # item_idからレビュー情報を取得
    def select_by_item_id(item_id)
        review_tag = ReviewTag.new()
        result_reviews = []
        reviews = Review.where(item_id: item_id)
        reviews.each do |review|
            # レビュータグを取得
            review.tag_names = review_tag.select_tag_names_by_review_id(review.id)
            result_reviews.push(review)
        end
        return result_reviews
    end
end

app/app/models/review_tag.rb
class ReviewTag < ApplicationRecord
    # review_idに紐づいているタグをタグ名で取得する
    def select_tag_names_by_review_id(review_id)
        tag_names = []
        results = ReviewTag.select('mst_review_tags.review_tag_name AS review_tag_name')
                           .joins('INNER JOIN mst_review_tags ON mst_review_tags.id = review_tags.review_tag_id')
                           .where(review_id: review_id)
        results.each do |result|
            tag_names.push(result.review_tag_name)
        end
        return tag_names
    end
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/app/controllers/detail_controller.rb
class DetailController < ApplicationController
    def index
        item_id = params[:id]
        item = Item.new
        # 現在のitemidの商品情報を取得
        @item_detail = item.select_by_id(item_id)
        # 商品が存在しない場合は404を返す
        if @item_detail.nil?
            redirect_to('/404.html')
            return
        end
        # 現在のitemidを除いた同じメーカーの他の商品を取得
        @same_maker_items = item.select_by_maker_exclude_item_id(@item_detail.item_maker_id, item_id)
    end
end

app/app/controllers/list_controller.rb
class ListController < ApplicationController
    def index
        sort_option = params[:sort]
        @items = Item.new.select_items(sort_option)
    end
end

app/app/controllers/review_controller.rb
class ReviewController < ApplicationController
    $rating_select_options = [1, 2, 3, 4, 5]

    def index
        item_id = params[:id]
        @item = Item.find_by(id: item_id)
        # 商品が存在しない場合は404を返す
        if @item.nil?
            redirect_to('/404.html')
            return
        end
        @reviews = Review.new.select_by_item_id(item_id)
    end

    def new
        item_id = params[:id]
        @item = Item.find_by(id: item_id)
        # 商品が存在しない場合は404を返す
        if @item.nil?
            redirect_to('/404.html')
            return
        end
        @review_form = ReviewForm.new
    end
    
    def create
        # パラメータ受け取り
        review_params = params.require(:review_form).permit(:reviewer_name,
                                                            :review_comment,
                                                            :price_rating,
                                                            :design_rating,
                                                            :quality_rating)
        @review_form = ReviewForm.new(review_params)
        @review_form.review_tag_ids = params[:review_form][:review_tag_ids]
        @review_form.item_id = params[:id]
        # バリデーション
        is_valid = @review_form.valid?
        if is_valid then
            # レビューをDBに保存
            is_success = @review_form.save
            if is_success then
                redirect_to reviews_url,    notice: "レビューが投稿されました"
            else
                redirect_to review_new_url, alert: "エラーが発生したため、レビューの投稿に失敗しました"
            end
        else
            # バリデーションエラーの場合はエラーメッセージを返す
            redirect_to review_new_url, alert: "入力情報が不完全のため、レビューが登録できませんでした", flash: @review_form.get_error_flashes
        end
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/detail_helper.rb
module DetailHelper
end

app/app/helpers/list_helper.rb
module ListHelper
end

app/app/helpers/review_helper.rb
module ReviewHelper
end

app/app/views/detail/index.html.erb
<div class="continer">
    <%= image_tag "/assets/#{@item_detail.item_image_path}", size: '400x400' %>
    <h1><%= @item_detail.item_name %></h1>
    <a>商品ID: <%= @item_detail.item_id %></a><br>
    <a>価格: ￥<%= @item_detail.item_price %></a><br>
    <a>商品説明: <%= @item_detail.item_sentence %></a><br>
    <a>メーカー: <%= @item_detail.maker_name %></a><br>
    <a>メーカー説明: <%= @item_detail.maker_sentence %></a><br>
    <a>カテゴリ: <%= @item_detail.category_name %></a><br>
    <a>投稿レビュー数: <%= @item_detail.review_count %></a><br>
    <a>レビュー評価の平均: <%= @item_detail.review_rating %> / 5</a><br>
    <%= link_to 'レビューを見る', reviews_path(@item_detail.item_id) %>
    <h2 class="mt-5">この商品のメーカーの他の商品</h2>
    <div class="row">
        <% @same_maker_items.each do |item| %>
            <div class="col-md-2 mt-2">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title"><%= item.item_name %></h5>
                        <a>商品ID: <%= item.item_id %></a><br>
                        <a>商品説明: <%= item.item_sentence %></a><br>
                        <a>メーカー: <%= item.maker_name %></a><br>
                        <a>投稿レビュー数: <%= item.review_count %></a><br>
                        <a>レビュー評価の平均: <%= item.review_rating %> / 5</a><br>
                        <%= link_to '商品詳細へ', item_detail_path(item.item_id) %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FAKE EC SITE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= link_to 'FAKE EC SITE', item_list_path %><br>
    <b class="text-success"><%= notice %></b>
    <b class="text-danger"><%= alert %></b>
    <%= yield %>
  </body>
</html>

app/app/views/list/index.html.erb
<div class="continer">
    <h1>商品一覧</h1>
    <%= link_to '評価の高い順に並び替え', item_list_path(sort: 'rating') %><br>
    <%= link_to 'レビューの多い順に並び替え', item_list_path(sort: 'review') %><br>
    <%= link_to '商品の新しい順に並び替え', item_list_path(sort: 'latest') %><br>
    <div class="row mt-4">
        <% @items.each do |item| %>
            <div class="col-md-2 mt-2">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title"><%= item.item_name %></h5>
                        <a>商品ID: <%= item.item_id %></a><br>
                        <a>商品説明: <%= item.item_sentence %></a><br>
                        <a>メーカー: <%= item.maker_name %></a><br>
                        <a>投稿レビュー数: <%= item.review_count %></a><br>
                        <a>レビュー評価の平均: <%= item.review_rating %> / 5</a><br>
                        <%= link_to '商品詳細へ', item_detail_path(item.item_id) %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/app/views/review/index.html.erb
<div class="continer">
    <%= link_to "#{@item.item_name}の商品ページ", item_detail_path(@item.id) %>
    <h2><%= @item.item_name %>に投稿されたレビュー</h2>
    <div class="row mt-4">
        <% if @reviews.count == 0 then %>
            <h4>この商品にはまだレビューがありません</h4>
        <% else %>
            <% @reviews.each do |review| %>
                <div class="col-md-2 mt-2">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title"><%= review.reviewer_name %> さんのレビュー</h5>
                            <a>コメントタグ: </a>
                            <% review.tag_names.each do |tag_name| %>
                                <a>#<%= tag_name %> </a>
                            <% end %><br>
                            <a>コメント: <%= review.review_comment %></a><br><br>
                            <h6 class="card-title">総合評価: <%= review.review_rating %> / 5</h6>
                            <a>価格評価: <%= review.price_rating %> / 5</a><br>
                            <a>デザイン評価: <%= review.design_rating %> / 5</a><br>
                            <a>品質評価: <%= review.quality_rating %> / 5</a><br>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
    <%= link_to "#{@item.item_name}のレビューを投稿する", review_new_path(@item.id) %>
</div>

app/app/views/review/new.html.erb
<div class="continer">
    <%= link_to "#{@item.item_name}の商品ページ", item_detail_path(@item.id) %><br>
    <%= link_to "#{@item.item_name}のレビュー一覧", reviews_path(@item.id) %>
    <h2 class="mt-4">レビューを投稿する</h2>
    <%= form_with(model: @review_form, url: review_create_path(@item.id)) do |form| %>
        <div class="mt-2">
            <%= form.label(:reviewer_name, 'お名前', class: 'fw-bold') %>
            <%= form.text_field(:reviewer_name, value: flash[:old_reviewer_name]) %>
            <% unless flash[:error_message_reviewer_name].nil? then %>
                <% flash[:error_message_reviewer_name].each do |message| %>
                    <br><b class="text-danger"><%= message %></b>
                <% end %>
            <% end %>
        </div>
        <div class="mt-2">
            <%= form.label(:review_tag_ids, 'コメントタグ(複数チェック可能)', class: 'fw-bold') %>
            <%= form.collection_check_boxes(:review_tag_ids, MstReviewTag.all, :id, :review_tag_name, { checked: flash[:old_review_tag_ids], include_hidden: false }) %>
            <% unless flash[:error_message_review_tag_ids].nil? then %>
                <% flash[:error_message_review_tag_ids].each do |message| %>
                    <br><b class="text-danger"><%= message %></b>
                <% end %>
            <% end %>
        </div>
        <div class="mt-2">
            <%= form.label(:review_comment, 'コメント', class: 'align-top fw-bold') %>
            <%= form.text_area(:review_comment, value: flash[:old_review_comment]) %>
            <% unless flash[:error_message_review_comment].nil? then %>
                <% flash[:error_message_review_comment].each do |message| %>
                    <br><b class="text-danger"><%= message %></b>
                <% end %>
            <% end %>
        </div>
        <div class="mt-2">
            <%= form.label(:price_rating, '価格評価(5段階)', class: 'fw-bold') %>
            <%= form.select(:price_rating, $rating_select_options, { include_blank: false, selected: flash[:old_price_rating].nil? ? 3 : flash[:old_price_rating] }) %>
            <% unless flash[:error_message_price_rating].nil? then %>
                <% flash[:error_message_price_rating].each do |message| %>
                    <br><b class="text-danger"><%= message %></b>
                <% end %>
            <% end %>
        </div>
        <div class="mt-2">
            <%= form.label(:design_rating, 'デザイン評価(5段階)', class: 'fw-bold') %>
            <%= form.select(:design_rating, $rating_select_options, { include_blank: false, selected: flash[:old_design_rating].nil? ? 3 : flash[:old_design_rating] }) %>
            <% unless flash[:error_message_design_rating].nil? then %>
                <% flash[:error_message_design_rating].each do |message| %>
                    <br><b class="text-danger"><%= message %></b>
                <% end %>
            <% end %>
        </div>
        <div class="mt-2">
            <%= form.label(:quality_rating, '品質評価(5段階)', class: 'fw-bold') %>
            <%= form.select(:quality_rating, $rating_select_options, { include_blank: false, selected: flash[:old_quality_rating].nil? ? 3 : flash[:old_quality_rating] }) %>
            <% unless flash[:error_message_quality_rating].nil? then %>
                <% flash[:error_message_quality_rating].each do |message| %>
                    <br><b class="text-danger"><%= message %></b>
                <% end %>
            <% end %>
        </div>
        <div class="mt-2">
            <%= form.submit('レビューを投稿') %>
        </div>    
    <% end %>
</div>